/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador;

import Clases.Libro;
import DataStructures.AVLNode;
import Inicio.InicioSesion;
import static Inicio.InicioSesion.library;
import static Inicio.InicioSesion.usuarioLogeado;
import static Inicio.InicioSesion.LibrosAgregados;
import static Inicio.InicioSesion.LibrosModificados;
import static Inicio.InicioSesion.LibrosEliminados;
import static Inicio.InicioSesion.CategoriasAgregadas;
import static Inicio.InicioSesion.CategoriasEliminadas;
import static Inicio.InicioSesion.userTable;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author juanp
 */
public class Biblioteca extends javax.swing.JFrame {

    /**
     * Creates new form Biblioteca
     */
    public Biblioteca() {
        initComponents();
        setLocationRelativeTo(null);
        buttonGroup1.add(rbAgregar);
        buttonGroup1.add(rbModificar);
        buttonGroup1.add(rbEliminar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rbAgregar = new javax.swing.JRadioButton();
        rbModificar = new javax.swing.JRadioButton();
        rbEliminar = new javax.swing.JRadioButton();
        txtBusquedaLibros = new javax.swing.JTextField();
        cbxResults = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSearchBooks = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtAccept = new javax.swing.JButton();
        btnOwnbooks = new javax.swing.JButton();
        lblGenerelCategories = new javax.swing.JButton();
        btnOwnCategories = new javax.swing.JButton();
        txtCategorySearch = new javax.swing.JTextField();
        btnGeneralBooks = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLenguage = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEdition = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblImagen = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnChangeCategoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel5.setText("Biblioteca");

        rbAgregar.setSelected(true);
        rbAgregar.setText("Agregar");
        rbAgregar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbAgregarStateChanged(evt);
            }
        });
        rbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAgregarActionPerformed(evt);
            }
        });

        rbModificar.setText("Modificar");
        rbModificar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbModificarStateChanged(evt);
            }
        });
        rbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbModificarActionPerformed(evt);
            }
        });

        rbEliminar.setText("Eliminar");
        rbEliminar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbEliminarStateChanged(evt);
            }
        });
        rbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEliminarActionPerformed(evt);
            }
        });

        txtBusquedaLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaLibrosActionPerformed(evt);
            }
        });

        cbxResults.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxResultsItemStateChanged(evt);
            }
        });
        cbxResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxResultsActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar");

        jLabel2.setText("Resultados");

        btnSearchBooks.setText("Buscar");
        btnSearchBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBooksActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtAccept.setText("Finalizar");
        txtAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcceptActionPerformed(evt);
            }
        });

        btnOwnbooks.setText("Libros Propios");
        btnOwnbooks.setMaximumSize(new java.awt.Dimension(140, 32));
        btnOwnbooks.setMinimumSize(new java.awt.Dimension(140, 32));
        btnOwnbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOwnbooksActionPerformed(evt);
            }
        });

        lblGenerelCategories.setText("Categorias");
        lblGenerelCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblGenerelCategoriesActionPerformed(evt);
            }
        });

        btnOwnCategories.setText("Categorias Propias");
        btnOwnCategories.setMaximumSize(new java.awt.Dimension(140, 32));
        btnOwnCategories.setMinimumSize(new java.awt.Dimension(140, 32));
        btnOwnCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOwnCategoriesActionPerformed(evt);
            }
        });

        btnGeneralBooks.setText("Libros");
        btnGeneralBooks.setMaximumSize(new java.awt.Dimension(140, 32));
        btnGeneralBooks.setMinimumSize(new java.awt.Dimension(140, 32));
        btnGeneralBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralBooksActionPerformed(evt);
            }
        });

        jLabel3.setText("ISBN");

        jLabel4.setText("Titulo");

        jLabel6.setText("Autor");

        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });
        txtISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtISBNKeyTyped(evt);
            }
        });

        jLabel7.setText("Categoria");

        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtYearKeyTyped(evt);
            }
        });

        jLabel8.setText("Año");

        jLabel9.setText("Editorial");

        txtLenguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLenguageActionPerformed(evt);
            }
        });

        jLabel11.setText("Edicion");

        txtEdition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditionKeyTyped(evt);
            }
        });

        jLabel10.setText("Idioma");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(758, 335));
        jScrollPane1.setViewportView(lblImagen);

        jLabel12.setText("Categoria");

        btnChangeCategoria.setText("Modificar Categoria");
        btnChangeCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(rbModificar)
                        .addGap(18, 18, 18)
                        .addComponent(rbEliminar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBusquedaLibros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(btnSearchBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbxResults, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnOwnCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblGenerelCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnOwnbooks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                        .addComponent(btnGeneralBooks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEdition))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnChangeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLenguage, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(336, 336, 336))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAgregar)
                    .addComponent(rbModificar)
                    .addComponent(rbEliminar)
                    .addComponent(txtBusquedaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchBooks))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOwnCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGenerelCategories)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCategorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOwnbooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGeneralBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChangeCategoria)
                            .addComponent(txtAccept)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLenguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAgregarActionPerformed

    private void rbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEliminarActionPerformed

    private void rbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbModificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcceptActionPerformed
        // TODO add your handling code here:
        long isbn = Long.parseLong(txtISBN.getText());
        String title = txtTitle.getText();
        String author = txtAuthor.getText();
        String editorial = txtEditorial.getText();
        String category = txtCategory.getText();
        int year = Integer.parseInt(txtYear.getText());
        int edition = Integer.parseInt(txtYear.getText());
        String lenguage = txtLenguage.getText();
        long carnet = usuarioLogeado.getCarnet();
        if (rbAgregar.isSelected()) {
            AVLNode node = library.searchCategory(txtCategory.getText());
            Libro newBook = new Libro(isbn, title, author, editorial, year, edition, category, lenguage, carnet);
            if (node == null) {
                library.insertBook(newBook);
                usuarioLogeado.agregarLibro(newBook);
                LibrosAgregados.add(newBook);
                JOptionPane.showMessageDialog(null, "Libro agregado exitosamente!", "Libro agregado", JOptionPane.INFORMATION_MESSAGE);

            } else {
                if (node.libros.buscarLibroISBN(isbn) == null) {
                    library.insertBook(newBook);
                    usuarioLogeado.agregarLibro(newBook);
                    LibrosAgregados.add(newBook);
                    JOptionPane.showMessageDialog(null, "Libro agregado exitosamente!", "Libro agregado", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    System.out.println("Libro ya existe");
                }
            }
            limpiar();
        } else if (rbModificar.isSelected()) {
            Libro book = library.searchBooks(isbn);
            if (book.getCarnet() == usuarioLogeado.getCarnet()) {
                Libro reemplazo = new Libro(isbn, title, author, editorial, year, edition, category, lenguage, carnet);
                library.deleteBook(isbn);
                LibrosEliminados.add(isbn);
                usuarioLogeado.getLibros().deleteBook(isbn);
                library.insertBook(reemplazo);
                usuarioLogeado.agregarLibro(reemplazo);
                LibrosAgregados.add(reemplazo);
                limpiar();
                JOptionPane.showMessageDialog(null, "Libro modificado exitosamente!", "Libro modificado", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "No puede modificar el libro, no es de su biblioteca", "Error en la modificación del libro", JOptionPane.ERROR_MESSAGE);
                limpiar();
            }
        } else {
            Libro book = library.searchBooks(isbn);
            if (book.getCarnet() == usuarioLogeado.getCarnet()) {
                int i = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar el libro?", "Eliminar libro", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    String respuesta = JOptionPane.showInputDialog(null, "¿Por qué lo eliminara?");
                    System.out.println("Se elimina el libro porque " + respuesta);
                    library.deleteBook(isbn);
                    LibrosEliminados.add(isbn);
                    usuarioLogeado.getLibros().deleteBook(isbn);
                    limpiar();
                    JOptionPane.showMessageDialog(null, "Eliminación Exitosa", "Libro eliminado", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No puede eliminar el libro, no es de su biblioteca", "Error en la eliminación del libro", JOptionPane.ERROR_MESSAGE);
                limpiar();
            }
        }
        jPanel1.updateUI();
        jScrollPane1.updateUI();
        lblImagen.updateUI();
    }//GEN-LAST:event_txtAcceptActionPerformed

    private void limpiar() {
        txtAuthor.setText("");
        txtCategory.setText("");
        txtEdition.setText("");
        txtEditorial.setText("");
        txtISBN.setText("");
        txtLenguage.setText("");
        txtTitle.setText("");
        txtYear.setText("");
    }

    ImageIcon image;

    private void btnOwnbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOwnbooksActionPerformed
        // TODO add your handling code here:
        if (!txtCategorySearch.getText().isEmpty()) {
            jScrollPane1.updateUI();
            lblImagen.setIcon(null);
            lblImagen.updateUI();
            String categoria = txtCategorySearch.getText();
            usuarioLogeado.getLibros().getBooks(categoria, String.valueOf(usuarioLogeado.getCarnet()));
            String rutaImagen = "BTree_Libros_" + categoria + "_" + String.valueOf(usuarioLogeado.getCarnet()) + ".png";
            image = new ImageIcon(rutaImagen);
            lblImagen.setIcon(image);
            jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
            lblImagen.revalidate();
            lblImagen.updateUI();
            jScrollPane1.updateUI();
            image.getImage().flush();
        }
    }//GEN-LAST:event_btnOwnbooksActionPerformed

    private void lblGenerelCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblGenerelCategoriesActionPerformed
        // TODO add your ha
        lblImagen.updateUI();
        jScrollPane1.updateUI();
        lblImagen.setIcon(null);
        library.generateDotTree("");
        image = new ImageIcon("AVL_Categorias.png");
        lblImagen.setIcon(image);
        jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        lblImagen.revalidate();
        lblImagen.updateUI();
        jScrollPane1.updateUI();
        image.getImage().flush();
    }//GEN-LAST:event_lblGenerelCategoriesActionPerformed

    private void btnOwnCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOwnCategoriesActionPerformed
        // TODO add your handling code here:
        lblImagen.updateUI();
        jScrollPane1.updateUI();
        lblImagen.setIcon(null);
        usuarioLogeado.getLibros().generateDotTree(String.valueOf(usuarioLogeado.getCarnet()));
        image = new ImageIcon("AVL_Categorias" + String.valueOf(usuarioLogeado.getCarnet()) + ".png");
        jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        lblImagen.setIcon(image);
        lblImagen.revalidate();
        lblImagen.updateUI();
        jScrollPane1.updateUI();
        image.getImage().flush();
    }//GEN-LAST:event_btnOwnCategoriesActionPerformed

    private void btnGeneralBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralBooksActionPerformed
        // TODO add your handling code here:
        if (!txtCategorySearch.getText().isEmpty()) {
            jScrollPane1.updateUI();
            lblImagen.setIcon(null);
            lblImagen.updateUI();
            String categoria = txtCategorySearch.getText();
            library.getBooks(categoria, "");
            ArrayList<Libro> libros = library.getBooksFromCategory(categoria);
            agregarLibros(libros);
            String rutaImagen = "BTree_Libros_" + categoria + "_.png";
            image = new ImageIcon(rutaImagen);
            lblImagen.setIcon(image);
            jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
            lblImagen.revalidate();
            lblImagen.updateUI();
            jScrollPane1.updateUI();
            image.getImage().flush();
        }
    }//GEN-LAST:event_btnGeneralBooksActionPerformed

    private void txtLenguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLenguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLenguageActionPerformed

    private void txtBusquedaLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaLibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaLibrosActionPerformed

    private void cbxResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxResultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxResultsActionPerformed

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void rbAgregarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbAgregarStateChanged
        // TODO add your handling code here:
        if (rbAgregar.isSelected() || rbModificar.isSelected()) {
            txtISBN.setEditable(true);
            txtTitle.setEditable(true);
            txtAuthor.setEditable(true);
            txtCategory.setEditable(true);
            txtEdition.setEditable(true);
            txtEditorial.setEditable(true);
            txtLenguage.setEditable(true);
            txtYear.setEditable(true);
        } else {
            txtISBN.setEditable(false);
            txtTitle.setEditable(false);
            txtAuthor.setEditable(false);
            txtCategory.setEditable(false);
            txtEdition.setEditable(false);
            txtEditorial.setEditable(false);
            txtLenguage.setEditable(false);
            txtYear.setEditable(false);
        }
    }//GEN-LAST:event_rbAgregarStateChanged

    private void txtISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtISBNKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (!Character.isDigit(validar)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtISBNKeyTyped

    private void txtYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (!Character.isDigit(validar)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtYearKeyTyped

    private void txtEditionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditionKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (!Character.isDigit(validar)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEditionKeyTyped

    private void rbModificarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbModificarStateChanged
        // TODO add your handling code here:
        if (rbAgregar.isSelected() || rbModificar.isSelected()) {
            txtISBN.setEditable(true);
            txtTitle.setEditable(true);
            txtAuthor.setEditable(true);
            txtCategory.setEditable(true);
            txtEdition.setEditable(true);
            txtEditorial.setEditable(true);
            txtLenguage.setEditable(true);
            txtYear.setEditable(true);
        } else {
            txtISBN.setEditable(true);
            txtTitle.setEditable(true);
            txtAuthor.setEditable(false);
            txtCategory.setEditable(false);
            txtEdition.setEditable(false);
            txtEditorial.setEditable(false);
            txtLenguage.setEditable(false);
            txtYear.setEditable(false);
        }
    }//GEN-LAST:event_rbModificarStateChanged

    private void rbEliminarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbEliminarStateChanged
        // TODO add your handling code here:
        if (rbAgregar.isSelected() || rbModificar.isSelected()) {
            txtISBN.setEditable(true);
            txtTitle.setEditable(true);
            txtAuthor.setEditable(true);
            txtCategory.setEditable(true);
            txtEdition.setEditable(true);
            txtEditorial.setEditable(true);
            txtLenguage.setEditable(true);
            txtYear.setEditable(true);
        } else {
            txtISBN.setEditable(true);
            txtTitle.setEditable(true);
            txtAuthor.setEditable(false);
            txtCategory.setEditable(false);
            txtEdition.setEditable(false);
            txtEditorial.setEditable(false);
            txtLenguage.setEditable(false);
            txtYear.setEditable(false);
        }
    }//GEN-LAST:event_rbEliminarStateChanged

    private void btnSearchBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBooksActionPerformed
        // TODO add your handling code here:
        cbxResults.removeAllItems();
        if (!txtBusquedaLibros.getText().isEmpty()) {
            String searchBook = txtBusquedaLibros.getText();
            if (isLong(searchBook)) {
                long code = Long.parseLong(searchBook);
                Libro book = library.searchBooks(code);
                if (book != null) {
                    colorcarCampos(book);
                } else {
                    ArrayList<Libro> libros = library.searchBooksbyName(searchBook);
                    agregarLibros(libros);

                }
            } else {
                ArrayList<Libro> libros = library.searchBooksbyName(searchBook);
                agregarLibros(libros);
            }
        }
    }//GEN-LAST:event_btnSearchBooksActionPerformed

    private void cbxResultsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxResultsItemStateChanged
        // TODO add your handling code here:
        if (cbxResults.getSelectedIndex() > 0) {
            System.out.println(cbxResults.getSelectedItem().toString());
            String[] vector = cbxResults.getSelectedItem().toString().split(";");
            Long isbn = Long.parseLong(vector[1]);
            Libro book = library.searchBooks(isbn);
            colorcarCampos(book);
        }
    }//GEN-LAST:event_cbxResultsItemStateChanged

    private void btnChangeCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeCategoriaActionPerformed
        // TODO add your handling code here:
        if (!txtCategorySearch.getText().isEmpty()) {
            lblImagen.revalidate();
            lblImagen.updateUI();
            jScrollPane1.updateUI();
            lblImagen.setIcon(null);
            if (rbAgregar.isSelected()) {
                library.agregarCategoria(txtCategorySearch.getText());
                usuarioLogeado.getLibros().agregarCategoria(txtCategorySearch.getText());
                CategoriasAgregadas.add(txtCategory.getText());
                JOptionPane.showMessageDialog(null, "Categoria agregada exitosamente!", "Categoria agregada", JOptionPane.INFORMATION_MESSAGE);

            } else if (rbEliminar.isSelected()) {
                int i = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar la categoria?", "Eliminar categoria", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    library.eliminarCategoria(txtCategorySearch.getText());
                    usuarioLogeado.getLibros().eliminarCategoria(txtCategorySearch.getText());
                    userTable.deleteUserCategory(txtCategorySearch.getText());
                    CategoriasEliminadas.add(txtCategorySearch.getText());
                    JOptionPane.showMessageDialog(null, "Eliminación Exitosa", "Categoria eliminada", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnChangeCategoriaActionPerformed

    private boolean isLong(String numero) {
        try {
            Long.parseLong(numero);
            return true;
        } catch (NumberFormatException e) {
            isInteger(numero);
            return false;
        }
    }

    private boolean isInteger(String numero) {
        try {
            Integer.parseInt(numero);
            return true;
        } catch (NumberFormatException e) {

            return false;
        }
    }

    private void colorcarCampos(Libro book) {
        txtAuthor.setText(book.getAutor());
        txtCategory.setText(book.getCategoria());
        txtEdition.setText(String.valueOf(book.getEdicion()));
        txtEditorial.setText(book.getEditorial());
        txtISBN.setText(String.valueOf(book.getISBN()));
        txtLenguage.setText(book.getIdioma());
        txtTitle.setText(book.getTitulo());
        txtYear.setText(String.valueOf(book.getAnio()));
    }

    private void agregarLibros(ArrayList<Libro> libros) {
        if (libros != null) {
            cbxResults.removeAllItems();
            cbxResults.addItem("Resultado de Busqueda:");
            for (Libro book : libros) {
                cbxResults.addItem(book.getTitulo() + ";" + book.getISBN());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeCategoria;
    private javax.swing.JButton btnGeneralBooks;
    private javax.swing.JButton btnOwnCategories;
    private javax.swing.JButton btnOwnbooks;
    private javax.swing.JButton btnSearchBooks;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxResults;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lblGenerelCategories;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JRadioButton rbAgregar;
    private javax.swing.JRadioButton rbEliminar;
    private javax.swing.JRadioButton rbModificar;
    private javax.swing.JButton txtAccept;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBusquedaLibros;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtCategorySearch;
    private javax.swing.JTextField txtEdition;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtLenguage;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
