/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador;

import Clases.Usuario;
import Inicio.InicioSesion;
import static Inicio.InicioSesion.usuarioLogeado;
import static Inicio.InicioSesion.userTable;
import static Inicio.InicioSesion.UsuariosAgregados;
import static Inicio.InicioSesion.UsuariosModficados;
import static Inicio.InicioSesion.UsuariosEliminados;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author juanp
 */
public class GestionUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form GestionUsuarios
     */
    public GestionUsuarios() {
        initComponents();
        setLocationRelativeTo(null);
        buttonGroup1.add(rbAdd);
        buttonGroup1.add(rbModify);
        buttonGroup1.add(rbDelete);
        userTable.generateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbAdd = new javax.swing.JRadioButton();
        rbModify = new javax.swing.JRadioButton();
        rbDelete = new javax.swing.JRadioButton();
        txtSearchCarnet = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCareer = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        txtConfirmPass = new javax.swing.JTextField();
        btnHash = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel5.setText("Usuarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(318, 318, 318))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        rbAdd.setSelected(true);
        rbAdd.setText("Agregar");
        rbAdd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbAddStateChanged(evt);
            }
        });
        rbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAddActionPerformed(evt);
            }
        });

        rbModify.setText("Modificar");
        rbModify.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbModifyStateChanged(evt);
            }
        });
        rbModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbModifyActionPerformed(evt);
            }
        });

        rbDelete.setText("Eliminar");
        rbDelete.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbDeleteStateChanged(evt);
            }
        });

        txtSearchCarnet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchCarnetKeyTyped(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(rbAdd)
                .addGap(18, 18, 18)
                .addComponent(rbModify)
                .addGap(18, 18, 18)
                .addComponent(rbDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearchCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAdd)
                    .addComponent(rbModify)
                    .addComponent(rbDelete)
                    .addComponent(txtSearchCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setText("Carnet:");

        txtCarnet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCarnetKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Carrera:");

        jLabel6.setText("Contraseña:");

        jLabel7.setText("Confirmar Contraseña:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnHash.setText("Tabla Hash");
        btnHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCareer)
                            .addComponent(txtConfirmPass, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHash, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCareer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnRegresar)
                    .addComponent(btnHash))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(lblImagen);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbModifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbModifyActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void rbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAddActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbAddActionPerformed

    private void rbAddStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbAddStateChanged
        // TODO add your handling code here:
        if (rbAdd.isSelected() || rbModify.isSelected()) {
            habilitarCeldas(true);
        } else if (rbDelete.isSelected()) {
            habilitarCeldas(false);
            colocarDatosPropios();
        } else {
            habilitarCeldas(true);
            colocarDatosPropios();
        }
    }//GEN-LAST:event_rbAddStateChanged

    private void txtCarnetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarnetKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (!Character.isDigit(validar)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCarnetKeyTyped

    private void rbModifyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbModifyStateChanged
        // TODO add your handling code here:
        if (rbAdd.isSelected()) {
            habilitarCeldas(true);
        } else if (rbDelete.isSelected()) {
            habilitarCeldas(false);
            colocarDatosPropios();
        } else {
            habilitarCeldas(true);
            colocarDatosPropios();
        }
    }//GEN-LAST:event_rbModifyStateChanged

    private void rbDeleteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbDeleteStateChanged
        // TODO add your handling code here:
        if (rbAdd.isSelected()) {
            habilitarCeldas(true);
        } else if (rbDelete.isSelected()) {
            habilitarCeldas(false);
        } else {
            habilitarCeldas(true);
            colocarDatosPropios();
        }
    }//GEN-LAST:event_rbDeleteStateChanged

    private void txtSearchCarnetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCarnetKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (!Character.isDigit(validar)) {
            evt.consume();
        }

    }//GEN-LAST:event_txtSearchCarnetKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if (rbAdd.isSelected()) {
            if (verifyData()) {
                String[] valores = obtenerDatos();
                if (valores[4].equals(valores[5])) {
                    Usuario nuevo = new Usuario(Long.valueOf(valores[0]), valores[1], valores[2], valores[3], valores[4]);
                    userTable.insertUser(nuevo);
                    UsuariosAgregados.add(nuevo);
                    JOptionPane.showMessageDialog(null, "Nuevo Usuario Agregado", "Datos Correctos", JOptionPane.INFORMATION_MESSAGE);
                    limpiarDatos();
                    colocarImagen();
                } else {
                    JOptionPane.showMessageDialog(null, "No se puede realizar el registro", "Datos Erroneos", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se puede realizar el registro", "Datos faltantes", JOptionPane.ERROR_MESSAGE);
            }
        } else if (rbDelete.isSelected()) {
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                userTable.deleteUser(Long.valueOf(txtCarnet.getText()));
                JOptionPane.showMessageDialog(null, "Usuario Eliminado", "Usuario Eliminado", JOptionPane.INFORMATION_MESSAGE);
                UsuariosEliminados.add(usuarioLogeado);
                usuarioLogeado = null;
                InicioSesion inicio = new InicioSesion();
                inicio.setVisible(true);
                dispose();

            }
        } else if (rbModify.isSelected()) {
            String[] valores = obtenerDatos();
            if (Long.valueOf(valores[0]) != usuarioLogeado.getCarnet()) {
                JOptionPane.showMessageDialog(null, "No se permite cambiar el valor de carnet", "Cambios no validos", JOptionPane.WARNING_MESSAGE);
                txtCarnet.setText(String.valueOf(usuarioLogeado.getCarnet()));
            } else if (!txtPassword.getText().equals(txtConfirmPass.getText())) {
                JOptionPane.showMessageDialog(null, "No se coinciden las contraseñas    ", "Cambios no validos", JOptionPane.WARNING_MESSAGE);
                txtPassword.setText("");
                txtConfirmPass.setText("");
            } else {
                usuarioLogeado.setNombre(valores[1]);
                usuarioLogeado.setApellido(valores[2]);
                usuarioLogeado.setCarrera(valores[3]);
                usuarioLogeado.setContrasena(valores[4]);
                UsuariosModficados.add(usuarioLogeado);
                JOptionPane.showMessageDialog(null, "Usuario modificado", "Modificacion", JOptionPane.INFORMATION_MESSAGE);
                limpiarDatos();
                colocarImagen();
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHashActionPerformed
        // TODO add your handling code here:
        jScrollPane1.updateUI();
        lblImagen.updateUI();
        lblImagen.setIcon(null);
        userTable.generateTable();
        colocarImagen();
    }//GEN-LAST:event_btnHashActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Usuario busqueda = userTable.search(Long.valueOf(txtSearchCarnet.getText()));
        if (busqueda != null) {
            txtCarnet.setText(String.valueOf(busqueda.getCarnet()));
            txtName.setText(busqueda.getNombre());
            txtLastName.setText(busqueda.getApellido());
            txtCareer.setText(busqueda.getCarrera());
            txtPassword.setText(busqueda.getMD5());
        } else {
            JOptionPane.showMessageDialog(null, "No se encontro el usuario", "Busqueda", JOptionPane.ERROR_MESSAGE);
            txtSearchCarnet.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private String[] obtenerDatos() {
        String[] valores = new String[6];
        valores[0] = txtCarnet.getText();
        valores[1] = txtName.getText();
        valores[2] = txtLastName.getText();
        valores[3] = txtCareer.getText();
        valores[4] = txtPassword.getText();
        valores[5] = txtConfirmPass.getText();
        return valores;
    }

    private Boolean verifyData() {
        if (txtCarnet.getText().isEmpty() || txtCareer.getText().isEmpty() || txtConfirmPass.getText().isEmpty()
                || txtLastName.getText().isEmpty() || txtName.getText().isEmpty() || txtPassword.getText().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    private void habilitarCeldas(Boolean habilitado) {
        txtCarnet.setEditable(habilitado);
        txtName.setEditable(habilitado);
        txtLastName.setEditable(habilitado);
        txtCareer.setEditable(habilitado);
        txtPassword.setEditable(habilitado);
        txtConfirmPass.setEditable(habilitado);
    }

    private void colocarDatosPropios() {
        txtCarnet.setText(String.valueOf(usuarioLogeado.getCarnet()));
        txtName.setText(usuarioLogeado.getNombre());
        txtLastName.setText(usuarioLogeado.getApellido());
        txtCareer.setText(usuarioLogeado.getCarrera());
        txtPassword.setText(usuarioLogeado.getContrasena());
    }

    private void limpiarDatos() {
        txtCarnet.setText("");
        txtName.setText("");
        txtLastName.setText("");
        txtCareer.setText("");
        txtPassword.setText("");
        txtConfirmPass.setText("");
    }

    ImageIcon image = new ImageIcon("HashTable_Usuarios.jpg");

    private void colocarImagen() {
        String ruta = "HashTable_Usuarios.jpg";
        File img = new File(ruta);
        BufferedImage bufferedImage = null;
        try {
            bufferedImage = ImageIO.read(img);
        } catch (IOException ex) {
            Logger.getLogger(GestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        image.setImage(bufferedImage);
        lblImagen.setIcon(image);
        lblImagen.revalidate();
        lblImagen.updateUI();
        jScrollPane1.updateUI();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnHash;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JRadioButton rbAdd;
    private javax.swing.JRadioButton rbDelete;
    private javax.swing.JRadioButton rbModify;
    private javax.swing.JTextField txtCareer;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtConfirmPass;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSearchCarnet;
    // End of variables declaration//GEN-END:variables
}
